### ISSUE TITLE
markdown转换为pdf报错

### ISSUE THREAD

**Issue by BIC-QA** [sailist/MarkTex#1]
File "c:\users\dell\appdata\local\programs\python\python37\lib\site-packages\marktex\markast\utils.py", line 78, in analyse
    res = xml_dict[tagl](tagl,content)
KeyError: 'b'

**Comment by zouwenhao** [comment]
> File "c:\users\dell\appdata\local\programs\python\python37\lib\site-packages\marktex\markast\utils.py", line 78, in analyse
> res = xml_dict[tagl](tagl,content)
> KeyError: 'b'

I meet same issue.

**Comment by sailist** [comment]
抱歉现在才看到这个错误提示，将原 md 文档贴出来或许便于查找问题所在

**Comment by sailist** [comment]
新版本已经重构完成并发布，您可以重新进行尝试
