### ISSUE TITLE
some bugs and recommend

### ISSUE THREAD

**Issue by xy-plus** [sailist/MarkTex#2]
一些 bug 和建议，希望能够帮助你们。

# Bug

## Bug1

错误代码位置：marktex/markast/utils.py#L578

`import matplotlib.pyplot as plt`

这句 import 写在 try 里，如果 import 失败会跳转到 except。except 不会对异常类型进行检察，会直接报 time out 错误。希望把所有 import 加到文件开头，并且在 install_requires 中加上 matplotlib 。

## Bug2

我使用的操作系统是 macOS ，通过 `pip install marktex -i https://pypi.python.org/pypi` 安装后，无法正常运行。错误原因是 marktex/markenv.tex 不存在。我从 GitHub 上拷贝了该文件后就可以正常运行了。

## Bug3

在跑示例程序 `run_example("./output/")` 的时候运行失败，原因是 `texfile.tex` 文件不存在，从 GitHub 上拷贝了该文件后可以正常运行。

> Bug2 和 Bug3 应该可以复现，我多次卸载重装后仍然会缺失这两个文件。

# 建议

## 说明 latex 文件所需的编译器

生成的 tex 文件使用了 ctex 包和 fontspec 包。所以无法通过 pdflatex、latex 或 lualatex进行编译，需要使用 xelatex 才能编译，希望能够在 readme 中说明（也许可以加一个 FQA）。

## 增加简单的 overleaf 的使用教程

因为 latex 的编译器太大，安装麻烦，所以我使用 overleaf 在线编辑 tex 文件。overleaf 的默认编译引擎是 pdflatex ，无法编译 marktex生成的文件。需要点击左上角的“菜单”图标，修改编译器，选择 xelatex 。以及，在 overleaf 上，ctex 的 fontset=windowsnew 参数无法支持，会导致编译超时，如果换成别的或删掉可能会是更好的选择。

以上。

非常喜欢 marktex ，特别好用，而且效果非常好，感谢你们。

**Comment by WenqiangX** [comment]
请问在哪里可以改成用xelatex编译?

**Comment by sailist** [comment]
谢谢你的建议！非常抱歉，之前我的Github的提示设置出了问题，导致我现在才发现这个 issue，我会在之后逐渐进行更改

**Comment by sailist** [comment]
再次感谢你的建议，这两天我重构了一遍代码，用更灵活的方式实现了 MD 语法树的解析和到 TeX 代码的转换，并在刚刚发布了新版本，您提及的bug和 在线编译器的问题均在文档和代码中有所更新，在我的电脑上运行无误，您可以重新再尝试一次！
