### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by MannixGu** [sailist/MarkTex#5]
File "D:\Program Files (x86)\Python3\lib\site-packages\marktex\texparser\base.py", line 33, in <module>
    with open(os.path.join(os.path.dirname(__file__), 'sign_to_tex.txt'), 'r', encoding='utf-8') as r:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Program Files (x86)\\Python3\\lib\\site-packages\\marktex\\texparser\\sign_to_tex.txt'

**Comment by Nativu5** [comment]
The same issue occurs to me!

**Comment by Nativu5** [comment]
A simple workaround before maintainer fixing the bug: 

1. Use pip to install the package.
2. Download  `marktex/texparser/sign_to_tex.txt` from this repo and put it into `Your_Python_Lib_Path\site-packages\marktex\texparser`.
3. After this you may be required for ` requests` package to be installed in the case a web image is included in your markdown doc.

Some suggestions to the maintainer:

* When packing up the src next time, may be you should include all the necessaries. 
* I would appreciate if you extend the Install&Usage part of `README`. I spent quite a lot time to figure out how to use this package and cope with latex errors. 

Thanks again for working on such a amazing project!

**Comment by sailist** [comment]
Thanks for your report, the bug is fixed and a new version(0.9.8, 0 means the version is still unstable) is released, you can run 
```shell
pip install marktex -U 
```
to reinstall it. 

Have a nice day.
