### ISSUE TITLE
代码块结尾有%

### ISSUE THREAD

**Issue by Tokubara** [sailist/MarkTex#8]
似乎`%`本来就会追加, 但是代码块的%会被显示.

**Comment by sailist** [comment]
这个项目暂时废弃了，写完后好久才发现 Markdown 解析是有 commonmark 标准在的，这个代码虽然重构了一次，但结构还是比较混乱，没有更新的价值了；之后（如果有时间），计划用编译器语法解析的方式代替正则解析的方式仿 [lute](https://github.com/88250/lute) 实现一版，顺便学习一下编译原理。

**Comment by Tokubara** [comment]
用perl脚本解决了这个问题, 脚本见[这个链接](https://gist.github.com/Tokubara/6f7dd45cad648223f214f33f05ccd84e), 不过路径等需要修改.
非常感谢您为开发这个项目作出的努力, 非常感谢这个项目, 带来了很多方便!
